/* Generated By:JJTree: Do not edit this line. ASTText.java */

package net.sourceforge.pmd.lang.jsp.ast;

public class ASTText extends AbstractJspNode {
    public ASTText(int id) {
        super(id);
    }

    public ASTText(JspParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JspParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
