/* Generated By:JavaCC: Do not edit this line. CPPParserConstants.java */
package net.sourceforge.pmd.cpd.cppast;

public interface CPPParserConstants {

  int EOF = 0;
  int LCURLYBRACE = 15;
  int RCURLYBRACE = 16;
  int LSQUAREBRACKET = 17;
  int RSQUAREBRACKET = 18;
  int LPARENTHESIS = 19;
  int RPARENTHESIS = 20;
  int SCOPE = 21;
  int COLON = 22;
  int SEMICOLON = 23;
  int COMMA = 24;
  int QUESTIONMARK = 25;
  int ELLIPSIS = 26;
  int ASSIGNEQUAL = 27;
  int TIMESEQUAL = 28;
  int DIVIDEEQUAL = 29;
  int MODEQUAL = 30;
  int PLUSEQUAL = 31;
  int MINUSEQUAL = 32;
  int SHIFTLEFTEQUAL = 33;
  int SHIFTRIGHTEQUAL = 34;
  int BITWISEANDEQUAL = 35;
  int BITWISEXOREQUAL = 36;
  int BITWISEOREQUAL = 37;
  int OR = 38;
  int AND = 39;
  int BITWISEOR = 40;
  int BITWISEXOR = 41;
  int AMPERSAND = 42;
  int EQUAL = 43;
  int NOTEQUAL = 44;
  int LESSTHAN = 45;
  int GREATERTHAN = 46;
  int LESSTHANOREQUALTO = 47;
  int GREATERTHANOREQUALTO = 48;
  int SHIFTLEFT = 49;
  int SHIFTRIGHT = 50;
  int PLUS = 51;
  int MINUS = 52;
  int STAR = 53;
  int DIVIDE = 54;
  int MOD = 55;
  int PLUSPLUS = 56;
  int MINUSMINUS = 57;
  int TILDE = 58;
  int NOT = 59;
  int DOT = 60;
  int POINTERTO = 61;
  int DOTSTAR = 62;
  int ARROWSTAR = 63;
  int AUTO = 64;
  int BREAK = 65;
  int CASE = 66;
  int CATCH = 67;
  int CHAR = 68;
  int CONST = 69;
  int CONTINUE = 70;
  int _DEFAULT = 71;
  int DELETE = 72;
  int DO = 73;
  int DOUBLE = 74;
  int ELSE = 75;
  int ENUM = 76;
  int EXTERN = 77;
  int FLOAT = 78;
  int FOR = 79;
  int FRIEND = 80;
  int GOTO = 81;
  int IF = 82;
  int INLINE = 83;
  int INT = 84;
  int LONG = 85;
  int NEW = 86;
  int PRIVATE = 87;
  int PROTECTED = 88;
  int PUBLIC = 89;
  int REDECLARED = 90;
  int REGISTER = 91;
  int RETURN = 92;
  int SHORT = 93;
  int SIGNED = 94;
  int SIZEOF = 95;
  int STATIC = 96;
  int STRUCT = 97;
  int CLASS = 98;
  int SWITCH = 99;
  int TEMPLATE = 100;
  int THIS = 101;
  int TRY = 102;
  int TYPEDEF = 103;
  int UNION = 104;
  int UNSIGNED = 105;
  int VIRTUAL = 106;
  int VOID = 107;
  int VOLATILE = 108;
  int WHILE = 109;
  int OPERATOR = 110;
  int TRUETOK = 111;
  int FALSETOK = 112;
  int THROW = 113;
  int OCTALINT = 114;
  int OCTALLONG = 115;
  int UNSIGNED_OCTALINT = 116;
  int UNSIGNED_OCTALLONG = 117;
  int DECIMALINT = 118;
  int DECIMALLONG = 119;
  int UNSIGNED_DECIMALINT = 120;
  int UNSIGNED_DECIMALLONG = 121;
  int HEXADECIMALINT = 122;
  int HEXADECIMALLONG = 123;
  int UNSIGNED_HEXADECIMALINT = 124;
  int UNSIGNED_HEXADECIMALLONG = 125;
  int FLOATONE = 126;
  int FLOATTWO = 127;
  int CHARACTER = 128;
  int STRING = 129;
  int ID = 131;

  int DEFAULT = 0;
  int IN_LINE_COMMENT = 1;
  int IN_COMMENT = 2;
  int PREPROCESSOR_OUTPUT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"//\"",
    "\"/*\"",
    "\"#\"",
    "\"\\n\"",
    "<token of kind 9>",
    "\"*/\"",
    "<token of kind 11>",
    "\"\\n\"",
    "\"\\\\\\n\"",
    "<token of kind 14>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"::\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"?\"",
    "\"...\"",
    "\"=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"!\"",
    "\".\"",
    "\"->\"",
    "\".*\"",
    "\"->*\"",
    "\"auto\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"delete\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extern\"",
    "\"float\"",
    "\"for\"",
    "\"friend\"",
    "\"goto\"",
    "\"if\"",
    "\"inline\"",
    "\"int\"",
    "\"long\"",
    "\"new\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"redeclared\"",
    "\"register\"",
    "\"return\"",
    "\"short\"",
    "\"signed\"",
    "\"sizeof\"",
    "\"static\"",
    "\"struct\"",
    "\"class\"",
    "\"switch\"",
    "\"template\"",
    "\"this\"",
    "\"try\"",
    "\"typedef\"",
    "\"union\"",
    "\"unsigned\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"operator\"",
    "\"true\"",
    "\"false\"",
    "\"throw\"",
    "<OCTALINT>",
    "<OCTALLONG>",
    "<UNSIGNED_OCTALINT>",
    "<UNSIGNED_OCTALLONG>",
    "<DECIMALINT>",
    "<DECIMALLONG>",
    "<UNSIGNED_DECIMALINT>",
    "<UNSIGNED_DECIMALLONG>",
    "<HEXADECIMALINT>",
    "<HEXADECIMALLONG>",
    "<UNSIGNED_HEXADECIMALINT>",
    "<UNSIGNED_HEXADECIMALLONG>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
    "\"finally\"",
    "<ID>",
  };

}
