@echo off
set CVSROOT=:ext:tomcopeland@cvs.pmd.sourceforge.net:/cvsroot/pmd
set CVS_RSH=c:\bin\ssh\ssh
set HOME=c:
set ANT_HOME=c:\ant151
set CLASSPATH=../build/
set CLASSPATH=%CLASSPATH%;../test-data/
set CLASSPATH=%CLASSPATH%;../
set CLASSPATH=%CLASSPATH%;c:\javacc2.1\bin\lib\JavaCC.zip
