/* Generated By:JJTree: Do not edit this line. ASTAbbrevReverseStep.java */

package net.sourceforge.pmd.jerry.ast.xpath;

public class ASTAbbrevReverseStep extends SimpleNode {
  public ASTAbbrevReverseStep(int id) {
    super(id);
  }

  public ASTAbbrevReverseStep(XPath2Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XPath2ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
