/* Generated By:JJTree: Do not edit this line. ASTForwardStep.java */

package net.sourceforge.pmd.jerry.ast.xpath;

public class ASTForwardStep extends SimpleNode {
  public ASTForwardStep(int id) {
    super(id);
  }

  public ASTForwardStep(XPath2Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XPath2ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
