/* Generated By:JJTree: Do not edit this line. ASTItemType.java */

package net.sourceforge.pmd.jerry.ast.xpath;

public class ASTItemType extends SimpleNode {
  public ASTItemType(int id) {
    super(id);
  }

  public ASTItemType(XPath2Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XPath2ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
