/* Generated By:JJTree: Do not edit this line. ASTPredicate.java */

package net.sourceforge.pmd.jerry.ast.xpath;

public class ASTPredicate extends SimpleNode {
  public ASTPredicate(int id) {
    super(id);
  }

  public ASTPredicate(XPath2Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XPath2ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
