/* Generated By:JJTree: Do not edit this line. ASTRangeExpr.java */

package net.sourceforge.pmd.jerry.ast.xpath;

public class ASTRangeExpr extends SimpleNode {
  public ASTRangeExpr(int id) {
    super(id);
  }

  public ASTRangeExpr(XPath2Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XPath2ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
