/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":pmd-core"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(project(":pmd-lang-test"))
    testImplementation(project(":pmd-test"))
    testImplementation(libs.com.github.oowekyala.treeutils.tree.matchers)
    testImplementation(libs.com.github.oowekyala.treeutils.tree.printers)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.stdlib)
    testImplementation(libs.org.jetbrains.annotations)
    testImplementation(libs.io.kotest.kotest.assertions.core.jvm)
    testImplementation(libs.io.kotest.kotest.runner.junit5.jvm)
}

description = "PMD Modelica"

java {
    withJavadocJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}