/*
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */

package net.sourceforge.pmd.lang.ast.impl.antlr4;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.Lexer;

import net.sourceforge.pmd.lang.ast.ParseException;
import net.sourceforge.pmd.lang.ast.Parser;
import net.sourceforge.pmd.lang.ast.RootNode;

/**
 * Generic Antlr parser adapter for all Antlr parsers. This wraps a parser
 * generated by antlr, soo {@link AntlrGeneratedParserBase}.
 *
 * <p>Error handling strategy:
 * <ul>
 *   <li><b>Lexer errors</b> (e.g. unrecognized tokens) and <b>Parser errors</b> (e.g. unexpected token structure)
 *       are collected and lexing/parsing continues.</li>
 *   <li>Further lexer/parser errors are collected as suppressed exceptions.</li>
 *   <li>The first occurred lexer/parser exception is thrown at the end and no rules are executed.</li>
 * </ul>
 *
 * <p>PMD reports the file as a {@code ProcessingError} and skips rule analysis for it.
 * All other files continue to be processed. Exit code 5 is returned by the CLI if
 * any processing errors occurred (suppressible with {@code --no-fail-on-error}).
 *
 * @param <N> Supertype of all nodes for the language, eg SwiftNode
 * @param <R> Type of the root node
 * @param <P> Type of the ANTLR generated parser class, eg SwiftParser
 *
 * @since 7.26.0
 */
public abstract class AntlrBaseParserWithErrorHandling<
    N extends AntlrNode<N>,
    R extends BaseAntlrInnerNode<N> & RootNode,
    P extends AntlrGeneratedParserBase<N>
    > extends AntlrBaseParser<N, R> implements Parser {

    @Override
    public R parse(ParserTask task) throws ParseException {
        CharStream cs = CharStreams.fromString(task.getSourceText(), task.getTextDocument().getFileId().getAbsolutePath());
        AntlrErrorListener errorListener = new AntlrErrorListener(task);
        Lexer lexer = getLexer(cs);
        lexer.removeErrorListeners();
        lexer.addErrorListener(errorListener.lexerErrorListener());

        P parser = getParser(lexer);
        parser.removeErrorListeners();
        parser.addErrorListener(errorListener.parserErrorListener());

        R parsed = parse(parser, task);
        if (errorListener.hasErrors()) {
            throw errorListener.getException();
        }
        return parsed;
    }

    @Override
    protected final R parse(Lexer parser, ParserTask task) {
        throw new IllegalStateException("This method shouldn't be called anymore.");
    }

    @Override
    protected abstract Lexer getLexer(CharStream source);

    protected abstract P getParser(Lexer lexer);

    protected abstract R parse(P parser, ParserTask task);
}
