/* Generated By:JJTree: Do not edit this line. ASTEnumDeclaration.java */

package net.sourceforge.pmd.ast;

public class ASTEnumDeclaration extends SimpleJavaAccessTypeNode {
    public ASTEnumDeclaration(int id) {
        super(id);
    }

    public ASTEnumDeclaration(JavaParser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
