/* Generated By:JJTree: Do not edit this line. ASTLiteral.java */

package net.sourceforge.pmd.ast;

public class ASTLiteral extends SimpleJavaTypeNode {
	
	private boolean isInt;
	private boolean isFloat;
	private boolean isChar;
	private boolean isString;
	
    public ASTLiteral(int id) {
        super(id);
    }

    public ASTLiteral(JavaParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
    
    public void setIntLiteral() {
    	this.isInt = true;
    }
    public boolean isIntLiteral() {
    	return isInt;
    }

    public void setFloatLiteral() {
    	this.isFloat = true;
    }
    public boolean isFloatLiteral() {
    	return isFloat;
    }

    public void setCharLiteral() {
    	this.isChar = true;
    }
    public boolean isCharLiteral() {
    	return isChar;
    }

    public void setStringLiteral() {
    	this.isString = true;
    }
    public boolean isStringLiteral() {
    	return isString;
    }
}
