/* Generated By:JJTree: Do not edit this line. ASTModifiers.java */

package net.sourceforge.pmd.ast;

public class ASTModifiers extends SimpleNode {
  public ASTModifiers(int id) {
    super(id);
  }

  public ASTModifiers(JavaParser p, int id) {
    super(p, id);
  }

    public boolean isDiscardable() {
        return true;
    }



  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
