/* Generated By:JJTree: Do not edit this line. ASTModifiers.java */

package net.sourceforge.pmd.ast;

public class ASTModifiers extends SimpleNode {
  public ASTModifiers(int id) {
    super(id);
  }

  public ASTModifiers(JavaParser p, int id) {
    super(p, id);
  }

    public boolean isDiscardable() {
        return true;
    }

    public void discardIfNecessary() {
        SimpleNode node = (SimpleNode)jjtGetParent();
        if (!(node.jjtGetChild(0) instanceof ASTModifiers)) {
            throw new RuntimeException("removeASTModifiersChild called but first child is not an ASTModifiers");
        }
        // TODO - can we just always discard the first node?
        if (node.jjtGetNumChildren() == 2) {
            // conventional forloop syntax
            node.children = new Node[] {node.children[1]};
        }
        if (node.jjtGetNumChildren() == 4) {
            // JDK 1.5 forloop syntax
            node.children = new Node[] {node.children[1], node.children[2], node.children[3]};
        }
    }

  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
