/* Generated By:JJTree: Do not edit this line. ASTResourceSpecification.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package net.sourceforge.pmd.ast;

public class ASTResourceSpecification extends SimpleJavaNode {
  public ASTResourceSpecification(int id) {
    super(id);
  }

  public ASTResourceSpecification(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=302a35714ff98375ee6f404b5814bb94 (do not edit this line) */
