/* Generated By:JJTree: Do not edit this line. ASTType.java */

package net.sourceforge.pmd.ast;

public class ASTType extends SimpleNode {
    public ASTType(int id) {
        super(id);
    }

    public ASTType(JavaParser p, int id) {
        super(p, id);
    }

    private boolean isArray;

    public boolean isArray() {
        return this.isArray;
    }

    public void setIsArray() {
        this.isArray = true;
    }

    /** Accept the visitor. **/
    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void dump(String prefix) {
        String out = toString(prefix) + ":";
        if (isArray()) {out += "(array)";}
        System.out.println(out);
        dumpChildren(prefix);
    }

}
