/* Generated By:JJTree: Do not edit this line. ASTType.java */

package net.sourceforge.pmd.ast;

public class ASTType extends SimpleNode {
    public ASTType(int id) {
        super(id);
    }

    public ASTType(JavaParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    private int arrayDepth;

    public void bumpArrayDepth() {
        arrayDepth++;
    }

    public int getArrayDepth() {
        return arrayDepth;
    }

    public boolean isArray() {
        return arrayDepth > 0;
    }

    public void dump(String prefix) {
        String out = "";
        if (arrayDepth > 0) {
            out += "(array";
            for (int i=0;i<arrayDepth;i++) {
                out += "[";
            }
            out += ")";
        }
        System.out.println(toString(prefix) + out);
        dumpChildren(prefix);
    }
}
