/* Generated By:JJTree: Do not edit this line. ASTJspDirective.java */

package net.sourceforge.pmd.jsp.ast;

public class ASTJspDirective extends SimpleNode {

    /* BEGIN CUSTOM CODE */

    /**
     * Name of the element-tag. Cannot be null.
     */
    private String name;

    /**
     * @return Returns the name.
     */
    public String getName() {
        return name;
    }

    /**
     * @param name The name to set.
     */
    public void setName(String name) {
        this.name = name;
    }

    /* (non-Javadoc)
     * @see com.applicationengineers.pmd4jsp.ast.SimpleNode#toString(java.lang.String)
     */
    public String toString(String prefix) {
        return super.toString(prefix) + " name=[" + name + "] ";
    }
/* END CUSTOM CODE */

    public ASTJspDirective(int id) {
        super(id);
    }

    public ASTJspDirective(JspParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(JspParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
