@echo off
set CVSROOT=:ext:tomcopeland@cvs.pmd.sourceforge.net:/cvsroot/pmd
set CVS_RSH=c:\bin\ssh\ssh
set HOME=c:
set ANT_HOME=c:\ant
set PATH=c:\j2sdk1.4.1_01\bin;%PATH%
set CLASSPATH=../build/
set CLASSPATH=%CLASSPATH%;../test-data/
set CLASSPATH=%CLASSPATH%;../
set CLASSPATH=%CLASSPATH%;../lib/xercesImpl-2.0.2.jar
set CLASSPATH=%CLASSPATH%;../lib/xmlParserAPIs-2.0.2.jar
set CLASSPATH=%CLASSPATH%;../lib/plugin.jar
set CLASSPATH=%CLASSPATH%;c:\ant\lib\ant.jar
set CLASSPATH=%CLASSPATH%;c:\ant\lib\junit.jar
