/**
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */
/* Generated By:JJTree: Do not edit this line. ASTDefaultValue.java */

package net.sourceforge.pmd.lang.java.ast;

import net.sourceforge.pmd.annotation.InternalApi;

public class ASTDefaultValue extends AbstractJavaNode {

    @InternalApi
    @Deprecated
    public ASTDefaultValue(int id) {
        super(id);
    }

    @InternalApi
    @Deprecated
    public ASTDefaultValue(JavaParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    @Override
    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
