/**
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */
/* Generated By:JJTree: Do not edit this line. ASTNullLiteral.java */

package net.sourceforge.pmd.lang.java.ast;

import java.util.Optional;


/**
 * A field access expression.
 *
 * <pre>
 *
 * FieldAccess ::=  {@link ASTPrimaryExpression PrimaryExpression} "." &lt;IDENTIFIER&gt;
 *               |  {@link ASTClassOrInterfaceType TypeName} "." &lt;IDENTIFIER&gt;
 *               (: Nothing can be done if this is not a :)
 *               |  {@link ASTAmbiguousName AmbiguousName} "." &lt;IDENTIFIER&gt;
 * </pre>
 */
public final class ASTFieldAccess extends AbstractJavaTypeNode implements ASTPrimaryExpression {
    ASTFieldAccess(int id) {
        super(id);
    }


    ASTFieldAccess(JavaParser p, int id) {
        super(p, id);
    }


    /**
     * Promotes an ambiguous name to the LHS of this node.
     */
    ASTFieldAccess(ASTAmbiguousName lhs, String fieldName) {
        super(JavaParserTreeConstants.JJTFIELDACCESS);
        this.jjtAddChild(lhs, 0);
        this.setImage(fieldName);
    }


    /**
     * Returns the expression to the left of the "." if it exists.
     */
    public Optional<ASTPrimaryExpression> getLhsExpression() {
        return Optional.ofNullable(getFirstChildOfType(ASTPrimaryExpression.class));
    }


    /**
     * Returns the type to the left of the "." if it exists.
     */
    public Optional<ASTClassOrInterfaceType> getLhsType() {
        return Optional.ofNullable(getFirstChildOfType(ASTClassOrInterfaceType.class));
    }


    /**
     * Returns the name of the field.
     */
    public String getFieldName() {
        return getImage();
    }


    @Override
    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }


    @Override
    public <T> void jjtAccept(SideEffectingVisitor<T> visitor, T data) {
        visitor.visit(this, data);
    }
}
