/**
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */
/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeExpression.java */

package net.sourceforge.pmd.lang.java.ast;

/**
 * Represents a multiplication, division, or modulo operation on
 * two or more values. This has a precedence greater than {@link ASTAdditiveExpression},
 * and lower than {@linkplain ASTUnaryExpression UnaryExpression}.
 *
 * <p>Note that the children of this node are not necessarily {@link ASTUnaryExpression}s,
 * rather, they are expressions with an operator precedence greater or equal to UnaryExpression.
 *
 * <pre class="grammar">
 *
 * MultiplicativeExpression ::= {@linkplain ASTUnaryExpression UnaryExpression} ( ( "*" | "/" | "%" ) {@linkplain ASTUnaryExpression UnaryExpression} )+
 *
 * </pre>
 */
public class ASTMultiplicativeExpression extends AbstractJavaTypeNode implements ASTExpression, LeftRecursiveNode {

    private BinaryOp operator;

    ASTMultiplicativeExpression(int id) {
        super(id);
    }

    ASTMultiplicativeExpression(JavaParser p, int id) {
        super(p, id);
    }

    @Override
    public void jjtClose() {
        super.jjtClose();

        // At this point the expression is fully left-recursive
        // If any of its left children are also AdditiveExpressions with the same operator,
        // we adopt their children to flatten the node

        AbstractJavaNode first = (AbstractJavaNode) jjtGetChild(0);
        if (first instanceof ASTMultiplicativeExpression && ((ASTMultiplicativeExpression) first).getOp() == getOp()) {
            flatten(0);
        }
    }


    @Override
    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }


    @Override
    public <T> void jjtAccept(SideEffectingVisitor<T> visitor, T data) {
        visitor.visit(this, data);
    }


    @Override
    public void setImage(String image) {
        super.setImage(image);
        this.operator = BinaryOp.fromImage(image);
    }

    /**
     * Returns the image of the operator, i.e. "*", "/" or "%".
     */
    public String getOperator() {
        return getImage();
    }

    public BinaryOp getOp() {
        return operator;
    }

}
