/**
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */
/* Generated By:JJTree: Do not edit this line. ASTPreIncrementExpression.java */

package net.sourceforge.pmd.lang.java.ast;

/**
 * Represents a pre-increment expression on a variable.
 * This has the same precedence as {@linkplain ASTUnaryExpression UnaryExpression}
 * and the like.
 *
 * <pre>
 *
 * PreIncrementExpression ::= "++" {@linkplain ASTPrimaryExpression PrimaryExpression}
 *
 * </pre>
 */
public class ASTPreIncrementExpression extends AbstractJavaTypeNode {
    public ASTPreIncrementExpression(int id) {
        super(id);
    }

    public ASTPreIncrementExpression(JavaParser p, int id) {
        super(p, id);
    }

    @Override
    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

}
