/**
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */
/* Generated By:JJTree: Do not edit this line. ASTSingleMemberAnnotation.java */

package net.sourceforge.pmd.lang.java.ast;

/**
 * Represents an annotation using the shorthand syntax for the default member.
 *
 * <pre>
 *
 * SingleMemberAnnotation ::=  "@" Name "(" {@linkplain ASTMemberValue MemberValue} ")"
 *
 * </pre>
 *
 * @see ASTMarkerAnnotation
 * @see ASTNormalAnnotation
 */
public class ASTSingleMemberAnnotation extends AbstractJavaTypeNode implements ASTAnnotation {
    public ASTSingleMemberAnnotation(int id) {
        super(id);
    }

    public ASTSingleMemberAnnotation(JavaParser p, int id) {
        super(p, id);
    }

    @Override
    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }


    @Override
    public <T> void jjtAccept(SideEffectingVisitor<T> visitor, T data) {
        visitor.visit(this, data);
    }


    /**
     * Returns the value of the default member
     * set by this annotation.
     */
    public ASTMemberValue getMemberValue() {
        return (ASTMemberValue) jjtGetChild(0);
    }

}
