/**
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */
/* Generated By:JJTree: Do not edit this line. ASTNullLiteral.java */

package net.sourceforge.pmd.lang.java.ast;

import java.util.Optional;


/**
 * The "this" expression. Related to the {@link ASTSuperExpression "super"} pseudo-expression.
 *
 * <pre>
 *
 * ThisExpression ::= "this"
 *                  | {@link ASTClassOrInterfaceType TypeName} "." "this"
 *
 * </pre>
 */
public final class ASTThisExpression extends AbstractJavaTypeNode implements ASTPrimaryExpression, LateInitNode {
    ASTThisExpression(int id) {
        super(id);
    }


    ASTThisExpression(JavaParser p, int id) {
        super(p, id);
    }


    public Optional<ASTClassOrInterfaceType> getQualifier() {
        return jjtGetNumChildren() > 0 ? Optional.of((ASTClassOrInterfaceType) jjtGetChild(0)) : Optional.empty();
    }


    /**
     * Accept the visitor. *
     */
    @Override
    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }


    @Override
    public <T> void jjtAccept(SideEffectingVisitor<T> visitor, T data) {
        visitor.visit(this, data);
    }


    @Override
    public void onInjectFinished() {
        // If this method is called, then a qualifier was injected
        ASTAmbiguousName name = (ASTAmbiguousName) jjtGetChild(0);
        this.replaceChildAt(0, name.forceTypeContext());
    }
}
