/**
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */
/* Generated By:JJTree: Do not edit this line. ASTType.java */

package net.sourceforge.pmd.lang.java.ast;

import net.sourceforge.pmd.annotation.Experimental;


/**
 * Represents a type reference.
 *
 * <pre>
 *
 * Type ::= {@linkplain ASTReferenceType ReferenceType}
 *        | {@linkplain ASTPrimitiveType PrimitiveType}
 *
 * </pre>
 *
 * Note: it is not exactly the same the "UnnanType" defined in JLS.
 */
public interface ASTType extends TypeNode {

    @Experimental
    default String getTypeImage() {
        return getImage();
    }


    default int getArrayDepth() {
        return 0;
    }


    default boolean isArrayType() {
        return this instanceof ASTArrayType;
    }


    default boolean isPrimitiveType() {
        return this instanceof ASTPrimitiveType;
    }


    default boolean isReferenceType() {
        return this instanceof ASTReferenceType;
    }


    default boolean isClassOrInterfaceType() {
        return this instanceof ASTClassOrInterfaceType;
    }


}
