/**
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */
/* Generated By:JJTree: Do not edit this line. ASTType.java */

package net.sourceforge.pmd.lang.java.ast;

public class ASTType extends AbstractJavaTypeNode {
    public ASTType(int id) {
        super(id);
    }

    public ASTType(JavaParser p, int id) {
        super(p, id);
    }

    private boolean varType;

    /**
     * Accept the visitor. *
     */
    @Override
    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public String getTypeImage() {
        if (isVarType()) {
            return getImage();
        }

        ASTClassOrInterfaceType refType = getFirstDescendantOfType(ASTClassOrInterfaceType.class);
        if (refType != null) {
            return refType.getImage();
        }
        return getFirstDescendantOfType(ASTPrimitiveType.class).getImage();
    }

    public int getArrayDepth() {
        if (jjtGetNumChildren() != 0
                && (jjtGetChild(0) instanceof ASTReferenceType || jjtGetChild(0) instanceof ASTPrimitiveType)) {
            return ((Dimensionable) jjtGetChild(0)).getArrayDepth();
        }
        throw new RuntimeException("ASTType.getArrayDepth called, but first child (of " + jjtGetNumChildren()
                + " total children) is neither a primitive nor a reference type.");
    }

    public boolean isArray() {
        return getArrayDepth() > 0;
    }

    void setVarType(boolean varType) {
        this.varType = varType;
    }

    /**
     * If true, this type represents a type of a local variable declaration, which
     * uses the java10 "var" type inference.
     */
    public boolean isVarType() {
        return varType;
    }
}
