package ant.java;

public class PMDTaskTestExample {

    // must be 100+ lines long
    public void veryLongMethod() {
        int a;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
        a -= 1;
        a += 1;
    }

    private int testField; // this will trigger a "Fields should be declared at top"
}