/*
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */

package net.sourceforge.pmd.lang.kotlin.ast;

import org.checkerframework.checker.nullness.qual.NonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

import net.sourceforge.pmd.annotation.Experimental;
import net.sourceforge.pmd.lang.LanguageVersion;
import net.sourceforge.pmd.lang.ast.AstInfo;
import net.sourceforge.pmd.lang.ast.AstVisitor;
import net.sourceforge.pmd.lang.ast.Node;
import net.sourceforge.pmd.lang.ast.NodeStream;
import net.sourceforge.pmd.lang.ast.RootNode;
import net.sourceforge.pmd.lang.document.FileLocation;
import net.sourceforge.pmd.lang.document.TextDocument;
import net.sourceforge.pmd.lang.document.TextRegion;
import net.sourceforge.pmd.lang.rule.xpath.NoAttribute;
import net.sourceforge.pmd.util.DataMap;

/**
 * Base class for companion classes that allow to define additional attributes on
 * KotlinNodes generated by ANTLR.
 *
 * <p>The concrete subclasses are returned by {@link KotlinInnerNode#attributes(Class)}
 * for usage in Java-based rules. The attributes defined in the subclasses are
 * automatically available as XPath-Attributes.
 *
 * <p>Additionally, common attributes for multiple types can be defined as
 * interfaces, e.g. {@link HasModifiers} and {@link HasSimpleIdentifier}.
 *
 * @param <T> the corresponding ANTLR node
 * @since 7.25.0
 * @experimental For Kotlin only, might be moved to pmd-core, if it proves useful
 */
@Experimental
public abstract class AttributeView<T extends KotlinNode> implements Node {
    protected final T node;

    public AttributeView(T node) {
        this.node = node;
    }

    public final T getNode() {
        return node;
    }

    @Experimental
    public static @Nullable AttributeView<?> create(KotlinNode kotlinNode) {
        final AttributeView<?> result;
        if (kotlinNode instanceof KotlinParser.KtImportHeader) {
            result = new KtImportHeaderAttributes((KotlinParser.KtImportHeader) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtImportAlias) {
            result = new KtImportAliasAttributes((KotlinParser.KtImportAlias) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtClassDeclaration) {
            result = new KtClassDeclarationAttributes((KotlinParser.KtClassDeclaration) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtClassParameter) {
            result = new KtClassParameterAttributes((KotlinParser.KtClassParameter) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtFunctionDeclaration) {
            result = new KtFunctionDeclarationAttributes((KotlinParser.KtFunctionDeclaration) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtPropertyDeclaration) {
            result = new KtPropertyDeclarationAttributes((KotlinParser.KtPropertyDeclaration) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtVariableDeclaration) {
            result = new KtVariableDeclarationAttributes((KotlinParser.KtVariableDeclaration) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtCompanionObject) {
            result = new KtCompanionObjectAttributes((KotlinParser.KtCompanionObject) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtCatchBlock) {
            result = new KtCatchBlockAttributes((KotlinParser.KtCatchBlock) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtForStatement) {
            result = new KtForStatementAttributes((KotlinParser.KtForStatement) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtFunctionValueParameter) {
            result = new KtFunctionValueParameterAttributes((KotlinParser.KtFunctionValueParameter) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtUnescapedAnnotation) {
            result = new KtUnescapedAnnotationAttributes((KotlinParser.KtUnescapedAnnotation) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtSingleAnnotation) {
            result = new KtSingleAnnotationAttributes((KotlinParser.KtSingleAnnotation) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtDelegationSpecifier) {
            result = new KtDelegationSpecifierAttributes((KotlinParser.KtDelegationSpecifier) kotlinNode);
        } else if (kotlinNode instanceof KotlinParser.KtKotlinFile) {
            result = new KtKotlinFileAttributes((KotlinParser.KtKotlinFile) kotlinNode);
        } else {
            result = null;
        }
        return result;
    }

    // --- delegations for Node

    @Override
    public KotlinNode getChild(int index) {
        return node.getChild(index);
    }

    /**
     * @deprecated Since 7.25.0. Don't use getImage() or hasImageEqualTo()! See #4787.
     */
    @Override
    @Deprecated
    public boolean hasImageEqualTo(String image) {
        return node.hasImageEqualTo(image);
    }

    /**
     * @deprecated Since 7.25.0. Don't use getImage() or hasImageEqualTo()! See #4787.
     */
    @Override
    @NoAttribute
    @Deprecated
    public String getImage() {
        return null;
    }

    @Override
    public @NonNull RootNode getRoot() {
        return node.getRoot();
    }

    @Override
    public LanguageVersion getLanguageVersion() {
        return node.getLanguageVersion();
    }

    @Override
    public int compareLocation(Node other) {
        return node.compareLocation(other);
    }

    @Override
    public FileLocation getReportLocation() {
        return node.getReportLocation();
    }

    @Override
    public int getIndexInParent() {
        return node.getIndexInParent();
    }

    @Override
    public <R extends Node> NodeStream<R> ancestors(Class<? extends R> rClass) {
        return node.ancestors(rClass);
    }

    @Override
    public <P, R> R acceptVisitor(AstVisitor<? super P, ? extends R> visitor, P data) {
        return node.acceptVisitor(visitor, data);
    }

    @Override
    public @NonNull TextDocument getTextDocument() {
        return node.getTextDocument();
    }

    @Override
    public TextRegion getTextRegion() {
        return node.getTextRegion();
    }

    @Override
    public <R extends Node> NodeStream<R> children(Class<? extends R> rClass) {
        return node.children(rClass);
    }

    @Override
    public AstInfo<? extends RootNode> getAstInfo() {
        return node.getAstInfo();
    }

    @Override
    public <R extends Node> NodeStream.DescendantNodeStream<R> descendants(Class<? extends R> rClass) {
        return node.descendants(rClass);
    }

    @Override
    public int getBeginLine() {
        return node.getBeginLine();
    }

    @Override
    @NoAttribute
    public boolean isFindBoundary() {
        return node.isFindBoundary();
    }

    @Override
    public <R extends Node> R firstChild(Class<? extends R> rClass) {
        return node.firstChild(rClass);
    }

    @Override
    public int getBeginColumn() {
        return node.getBeginColumn();
    }

    @Override
    public String getXPathNodeName() {
        return node.getXPathNodeName();
    }

    @Override
    public int getEndLine() {
        return node.getEndLine();
    }

    @Override
    public int getEndColumn() {
        return node.getEndColumn();
    }

    @Override
    public int getNumChildren() {
        return node.getNumChildren();
    }

    @Override
    public DataMap<DataMap.DataKey<?, ?>> getUserMap() {
        return node.getUserMap();
    }

    @Override
    public @Nullable KotlinNode getFirstChild() {
        return node.getFirstChild();
    }

    @Override
    public KotlinNode getParent() {
        return node.getParent();
    }

    @Override
    public @Nullable KotlinNode getNextSibling() {
        return node.getNextSibling();
    }

    @Override
    public @Nullable KotlinNode getLastChild() {
        return node.getLastChild();
    }

    @Override
    public NodeStream<KotlinNode> asStream() {
        return node.asStream();
    }

    @Override
    public NodeStream<KotlinNode> children() {
        return node.children();
    }

    @Override
    public NodeStream.DescendantNodeStream<KotlinNode> descendants() {
        return node.descendants();
    }

    @Override
    public NodeStream.DescendantNodeStream<KotlinNode> descendantsOrSelf() {
        return node.descendantsOrSelf();
    }

    @Override
    public NodeStream<KotlinNode> ancestorsOrSelf() {
        return node.ancestorsOrSelf();
    }

    @Override
    public NodeStream<KotlinNode> ancestors() {
        return node.ancestors();
    }

    @Override
    public @Nullable KotlinNode getPreviousSibling() {
        return node.getPreviousSibling();
    }
}
