source 'https://rubygems.org/'

# bleeding edge from git
#gem 'pmdtester', :git => 'https://github.com/pmd/pmd-regression-tester.git', branch: 'main'
gem 'pmdtester', :git => 'https://github.com/adangel/pmd-regression-tester.git', branch: 'issue-148-violation-location'

#gem 'pmdtester'

gem 'logger'
gem 'ostruct'
gem 'base64'

# vim: syntax=ruby
