#!/bin/sh

is_cygwin() {
    case "$(uname)" in
        CYGWIN*|MINGW*)
            cygwin=true
            ;;
        *)
            # OS specific support.  $var _must_ be set to either true or false.
            if [ -z "$cygwin" ] ; then
              cygwin=false
            fi
            ;;
    esac
}

cygwin_paths() {
    # For Cygwin, switch paths to Windows format before running java
    if [ "$cygwin" = true ] ; then
        [ -n "$JAVA_HOME" ] && JAVA_HOME=$(cygpath --windows "$JAVA_HOME")
        [ -n "$JAVAFX_HOME" ] && JAVAFX_HOME=$(cygpath --windows "$JAVAFX_HOME")
        [ -n "$DIRECTORY" ] && DIRECTORY=$(cygpath --windows "$DIRECTORY")
        classpath=$(cygpath --path --windows "$classpath")
    fi
}

convert_cygwin_vars() {
    # If cygwin, convert to Unix form before manipulating
    if [ "$cygwin" = true ] ; then
        [ -n "$JAVA_HOME" ] && JAVA_HOME=$(cygpath --unix "$JAVA_HOME")
        [ -n "$JAVAFX_HOME" ] && JAVAFX_HOME=$(cygpath --unix "$JAVAFX_HOME")
        [ -n "$CLASSPATH" ] && CLASSPATH=$(cygpath --path --unix "$CLASSPATH")
    fi
}

java_heapsize_settings() {
    case "$HEAPSIZE" in
        [1-9]*[mgMG])
            HEAPSIZE="-Xmx$HEAPSIZE"
            ;;
        '')
            ;;
        *)
            echo "HEAPSIZE '$HEAPSIZE' unknown (try: 1024m)"
            exit 1
    esac
}

set_pmd_home_dir() {
  script_real_loc="$0"

  # see #4723 - allow calling as "bash pmd", when pmd is on the PATH
  if [ ! -e "$script_real_loc" ]; then
    script_real_loc=$(which "$script_real_loc")
  fi

  if [ ! -e "$script_real_loc" ]; then
    echo "Couldn't determine PMD_HOME path. Script location [$script_real_loc] does not exist"
    exit 1
  fi

  # Allow for symlinks to this script
  if [ -L "$script_real_loc" ]; then
    script_real_loc=$(readlink "$script_real_loc")
  fi

  # use the directory of the script (which is ..../bin)
  script_real_loc=$(dirname "$script_real_loc")
  # use the parent directory
  PMD_HOME="$script_real_loc/.."
  # make it normalized and fully qualified
  PMD_HOME=$(cd "$PMD_HOME" && pwd)
}

set_lib_dir() {
  if [ -z "$LIB_DIR" ]; then
    LIB_DIR="$PMD_HOME/lib"
  fi
}

check_lib_dir() {
  if [ ! -e "$LIB_DIR" ]; then
    echo "The jar directory [$LIB_DIR] does not exist"
  fi
}

set_conf_dir() {
  if [ -z "$CONF_DIR" ]; then
    CONF_DIR="$PMD_HOME/conf"
  fi
}

check_conf_dir() {
  if [ ! -e "$CONF_DIR" ]; then
    echo "The configuration directory [$CONF_DIR] does not exist"
  fi
}

script_exit() {
    echo "$1" >&2
    exit 1
}

check_java() {
  if ! java -version >/dev/null 2>&1; then
    script_exit "No java executable found in PATH"
  fi
}

determine_java_version() {
    all_props=$(java -XshowSettings:properties 2>&1)
    java_ver_normalized=$(echo "$all_props" | grep "java.version" | sed -n -e '{
      s/^.*java\.version *= *//
      # replace java versions java 1.7 and java 1.8 with 7 and 8
      s/^1\.\([78]\)/\1/
      # print what is left
      p
    }')
    # 1. component: java_version_feature is e.g. "8" for java 1.8, "9" for java 9, "10" for java 10, ...
    java_version_feature=$(echo "$java_ver_normalized" | sed -n -e 's/^\([0-9]\{1,\}\).*$/\1/p')
    # 3. component: update release counter
    java_version_update=$(echo "$java_ver_normalized" | sed -n -e 's/^\([0-9]\{1,\}\)\.\([0-9]\{1,\}\).\([0-9]\{1,\}\).*$/\3/p')
    # if there was no 3rd component, use "0"
    java_version_update=${java_version_update:="0"}

    java_home_property=$(echo "$all_props" | grep "java.home" | sed -n -e 's/^.*java\.home *= *\(.*\)$/\1/; p')
    java_has_javafx=0
    java_javafx_properties=
    if [ -e "$java_home_property/lib/javafx.properties" ]; then
      java_javafx_properties="$java_home_property/lib/javafx.properties"
      java_has_javafx=1
    elif [ -e "$java_home_property/jre/lib/javafx.properties" ]; then
      java_javafx_properties="$java_home_property/jre/lib/javafx.properties"
      java_has_javafx=1
    fi
}

jre_specific_vm_options() {
  if [ "$APPNAME" = "designer" ]
  then
    options=""

    if [ "$java_version_feature" -ge 9 ] && [ $java_has_javafx = 1 ]
    then
      # java9 and java10 from oracle contain javafx as a module
      # Azul provides builds which include javafx as well
      # Since Java 9, it is included as a module. But we run on the classpath (aka unnamed module) and
      # want to access the classes.
      #
      # for PMD Designer
      # in net.sourceforge.pmd.util.fxdesigner.util.controls.TreeViewWrapper.getVirtualFlow
      options="--add-opens javafx.controls/javafx.scene.control.skin=ALL-UNNAMED"
      # in net.sourceforge.pmd.util.fxdesigner.util.DesignerUtil.customBuilderFactory
      options="$options --add-opens javafx.fxml/com.sun.javafx.fxml.builder=ALL-UNNAMED"
      #
      # for RichtextFX
      options="$options --add-opens javafx.graphics/javafx.scene.text=ALL-UNNAMED"
      options="$options --add-opens javafx.graphics/com.sun.javafx.scene.text=ALL-UNNAMED"
      options="$options --add-opens javafx.graphics/com.sun.javafx.text=ALL-UNNAMED"
      options="$options --add-opens javafx.graphics/com.sun.javafx.geom=ALL-UNNAMED"
      #
      # for controlsfx
      options="$options --add-opens javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED"
      options="$options --add-opens javafx.base/com.sun.javafx.runtime=ALL-UNNAMED"
      options="$options --add-opens javafx.base/com.sun.javafx.event=ALL-UNNAMED"
      options="$options --add-opens javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED"

      if [ "$java_version_feature" -lt 17 ]
      then
        # Warn of remaining illegal accesses - only possible until java 16.
        # With Java 17+ this option has no effect anymore (https://openjdk.org/jeps/403).
        options="$options --illegal-access=warn"
      fi
    fi

    echo "$options"
  else
    echo ""
  fi
}

add_pmd_classpath() {
    if [ -n "$classpath" ]; then
        classpath="$classpath:$CONF_DIR:$LIB_DIR/*"
    else
        classpath="$CONF_DIR:$LIB_DIR/*"
    fi
}

add_openjfx_classpath() {
  if [ "$APPNAME" = "designer" ]
  then
    if [ $java_has_javafx = 1 ]
    then
      # almost nothing to do, javafx is bundled (either an old Oracle Java < 8u451 or an OpenJDK 8 Build from Azul)
      # still hadd the path where javafx.properties is located to the classpath, so that Designer's
      # net.sourceforge.pmd.util.fxdesigner.util.JavaFxUtil#getJavaFxVersion can find it.
      if [ -n "$classpath" ]; then
        classpath="$classpath:$(dirname "$java_javafx_properties")"
      else
        classpath="$(dirname "$java_javafx_properties")"
      fi
    elif [ "$java_version_feature" = "8" ] && [ "$java_version_update" -ge 451 ]
    then
      script_exit "
        JavaFX has been removed from Oracle Java 8 since Java 8u451. See https://www.oracle.com/javase/javafx.
        Use Java 11 or later with OpenJFX separately from https://openjfx.io/.
        Alternatively use an OpenJDK build from Azul with JavaFX bundled (JDK FX).
      "
    elif [ "$java_version_feature" -lt 10 ]
    then
      script_exit "
        For OpenJFX at least Java 10 is required.
      "
    else
      # openjfx is required for any openjdk builds which don't include JavaFX
      if [ -z "$JAVAFX_HOME" ]
      then
        script_exit "The environment variable JAVAFX_HOME is missing."
      else
        # The wildcard will include only jar files, but we need to access also
        # property files such as javafx.properties that lay bare in the dir
        if [ -n "$classpath" ]; then
          classpath="$classpath:$JAVAFX_HOME/lib/*:$JAVAFX_HOME/lib/"
        else
          classpath="$JAVAFX_HOME/lib/*:$JAVAFX_HOME/lib/"
        fi
      fi
    fi
  fi
}

APPNAME="$1"

is_cygwin

check_java

set_pmd_home_dir
set_lib_dir
check_lib_dir
set_conf_dir
check_conf_dir

convert_cygwin_vars

classpath=$CLASSPATH

add_pmd_classpath
determine_java_version
add_openjfx_classpath

cygwin_paths

java_heapsize_settings

# Note: we want word-splitting happening on PMD_JAVA_OPTS and jre_specific_vm_options
exec java \
  ${HEAPSIZE:+"$HEAPSIZE"} \
  $PMD_JAVA_OPTS $(jre_specific_vm_options) \
  -cp "$classpath" \
  net.sourceforge.pmd.cli.PmdCli "$@"
