/* Generated By:JJTree: Do not edit this line. ASTConditionalCompilationStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=net.sourceforge.pmd.lang.ast.AbstractNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.pmd.lang.plsql.ast;

public
class ASTConditionalCompilationStatement extends SimpleNode {
  public ASTConditionalCompilationStatement(int id) {
    super(id);
  }

  public ASTConditionalCompilationStatement(PLSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f9ecd7510c0e05c8f84327d4c88e83f7 (do not edit this line) */
