/* Generated By:JJTree: Do not edit this line. ASTdatabase_event.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.pmd.lang.plsql.ast;

public
class ASTdatabase_event extends SimpleNode {
  public ASTdatabase_event(int id) {
    super(id);
  }

  public ASTdatabase_event(PLSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b1bbd6f3f1a41d19cc491ed05ed1d55c (do not edit this line) */
