/* Generated By:JJTree: Do not edit this line. ASTEmbeddedSqlStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=net.sourceforge.pmd.lang.ast.AbstractNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.pmd.lang.plsql.ast;

public
class ASTEmbeddedSqlStatement extends SimpleNode {
  public ASTEmbeddedSqlStatement(int id) {
    super(id);
  }

  public ASTEmbeddedSqlStatement(PLSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=94dc099fe2425fcab7da92b835c23a88 (do not edit this line) */
