/* Generated By:JJTree: Do not edit this line. ASTinput.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.pmd.lang.plsql.ast;

import net.sourceforge.pmd.lang.ast.RootNode;

/*
 * Any class returned as to Viewer has to implement the RootNode interface.
 * Otherwise the application seems to work (the AST is displayed), but the 
 * XPath search fails to return any values. 
 */
public
class ASTinput extends SimpleNode implements RootNode  {
  public ASTinput(int id) {
    super(id);
  }

  public ASTinput(PLSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=52d66ee15cea425f5f06e62c99030f2b (do not edit this line) */
