/**
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */

/* Generated By:JJTree: Do not edit this line. ASTIfStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package net.sourceforge.pmd.lang.plsql.ast;

public class ASTIfStatement extends net.sourceforge.pmd.lang.plsql.ast.AbstractPLSQLNode{
  public ASTIfStatement(int id) {
    super(id);
  }

  public ASTIfStatement(PLSQLParser p, int id) {
    super(p, id);
  }

  private boolean hasElse;

  public void setHasElse() {
      this.hasElse = true;
  }

  public boolean hasElse() {
      return this.hasElse;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=593efca5606eb54375cc42fe11ab9f67 (do not edit this line) */
