/* Generated By:JJTree: Do not edit this line. ASTjavaInterfaceClass.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.pmd.lang.plsql.ast;

public
class ASTjavaInterfaceClass extends SimpleNode {
  public ASTjavaInterfaceClass(int id) {
    super(id);
  }

  public ASTjavaInterfaceClass(PLSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5008fdd8cd666d476a34ddd27a29eacf (do not edit this line) */
