/* Generated By:JJTree: Do not edit this line. ASTPackageSpecification.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=net.sourceforge.pmd.lang.ast.AbstractNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.pmd.lang.plsql.ast;

public
class ASTPackageSpecification extends SimpleNode implements OracleObject {
  public ASTPackageSpecification(int id) {
    super(id);
  }

  public ASTPackageSpecification(PLSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  /**
   * Gets the name of the Oracle Object.
   *
   * @return a String representing the name of the Oracle Object
   */
  @Override
  public String getObjectName() {
    return this.getImage();
   }
}
/* JavaCC - OriginalChecksum=7aed5a20069f8533d3ed042d523cbe47 (do not edit this line) */
