/* Generated By:JJTree: Do not edit this line. ASTPrimarySuffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.pmd.lang.plsql.ast;

public
class ASTPrimarySuffix extends SimpleNode {
  public ASTPrimarySuffix(int id) {
    super(id);
  }

  public ASTPrimarySuffix(PLSQLParser p, int id) {
    super(p, id);
  }

  private boolean isArguments;
  private boolean isArrayDereference;

  public void setIsArrayDereference() {
      isArrayDereference = true;
  }

  public boolean isArrayDereference() {
      return isArrayDereference;
  }

  public void setIsArguments() {
      this.isArguments = true;
  }

  public boolean isArguments() {
      return this.isArguments;
  }

  /**
   * Get the number of arguments for this primary suffix.  One should call
   * {@link #isArguments()} to see if there are arguments.  If this method is
   * called when there are no arguments it returns <code>-1</code>.
   * @return A non-negative argument number when there are arguments,
   * <code>-1</code> otherwise.
   */
  public int getArgumentCount() {
      if (!this.isArguments()) {
	  return -1;
      }
      return ((ASTArguments)jjtGetChild(jjtGetNumChildren()-1)).getArgumentCount();
  }




  /** Accept the visitor. **/
  public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=98bfc2f2a5fec5e786a4389293109709 (do not edit this line) */
