/* Generated By:JJTree: Do not edit this line. ASTSkip2NextOccurrence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.pmd.lang.plsql.ast;

public
class ASTSkip2NextOccurrence extends SimpleNode {
  public ASTSkip2NextOccurrence(int id) {
    super(id);
  }

  public ASTSkip2NextOccurrence(PLSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1baf4bf7bd4bfdaacf4d6c50f71c7773 (do not edit this line) */
