/* Generated By:JJTree: Do not edit this line. ASTtriggerUnit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.pmd.lang.plsql.ast;

public
class ASTtriggerUnit extends SimpleNode {
  public ASTtriggerUnit(int id) {
    super(id);
  }

  public ASTtriggerUnit(PLSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e92ac9edbfc4c5d07bf8ffd0fa97ae4e (do not edit this line) */
