/* Generated By:JJTree: Do not edit this line. ASTTriggerTimingPointSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=net.sourceforge.pmd.lang.ast.AbstractNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.pmd.lang.plsql.ast;

public
class ASTTriggerTimingPointSection extends SimpleNode {
  public ASTTriggerTimingPointSection(int id) {
    super(id);
  }

  public ASTTriggerTimingPointSection(PLSQLParser p, int id) {
    super(p, id);
  }

  
    @Override
    public int hashCode() {
      return getImage().hashCode() ;
	
    }

    @Override
    public String toString() {
        return "Timing Point Section " + getImage() + ", line " + getBeginLine() ;
    }

  /** Accept the visitor. **/
  public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fa4b3fb1b2d6602be88e303cd2e425e1 (do not edit this line) */
