/**
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */

/* Generated By:JJTree: Do not edit this line. ASTTypeSpecification.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package net.sourceforge.pmd.lang.plsql.ast;

public class ASTTypeSpecification extends net.sourceforge.pmd.lang.plsql.ast.AbstractPLSQLNode
implements OracleObject {
  public ASTTypeSpecification(int id) {
    super(id);
  }

  public ASTTypeSpecification(PLSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  /**
   * Gets the name of the Oracle Object.
   *
   * @return a String representing the name of the Oracle Object
   */
  @Override
  public String getObjectName() {
    return this.getImage();
   }
}
/* JavaCC - OriginalChecksum=71647f77a828bee6feba3ee70c44206c (do not edit this line) */
