/* Generated By:JavaCC: Do not edit this line. PLSQLParserTreeConstants.java Version 5.0 */
package net.sourceforge.pmd.lang.plsql.ast;

public interface PLSQLParserTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTSQLPLUSCOMMAND = 1;
  public int JJTGLOBAL = 2;
  public int JJTBLOCK = 3;
  public int JJTPACKAGESPECIFICATION = 4;
  public int JJTPACKAGEBODY = 5;
  public int JJTDECLARATIVEUNIT = 6;
  public int JJTDECLARATIVESECTION = 7;
  public int JJTCOMPILATIONDECLARATIONFRAGMENT = 8;
  public int JJTPROGRAMUNIT = 9;
  public int JJTOBJECTNAMEDECLARATION = 10;
  public int JJTFORMALPARAMETER = 11;
  public int JJTMETHODDECLARATION = 12;
  public int JJTMETHODDECLARATOR = 13;
  public int JJTFORMALPARAMETERS = 14;
  public int JJTVARIABLEORCONSTANTDECLARATOR = 15;
  public int JJTVARIABLEORCONSTANTDECLARATORID = 16;
  public int JJTVARIABLEORCONSTANTINITIALIZER = 17;
  public int JJTDATATYPE = 18;
  public int JJTCOMPILATIONDATATYPE = 19;
  public int JJTCOLLECTIONTYPENAME = 20;
  public int JJTSCALARDATATYPENAME = 21;
  public int JJTDATETIMELITERAL = 22;
  public int JJTEXCEPTIONHANDLER = 23;
  public int JJTSKIP2NEXTTERMINATOR = 24;
  public int JJTSKIP2NEXTOCCURRENCE = 25;
  public int JJTSKIPPASTNEXTOCCURRENCE = 26;
  public int JJTSKIP2NEXTTOKENOCCURRENCE = 27;
  public int JJTSKIPPASTNEXTTOKENOCCURRENCE = 28;
  public int JJTREAD2NEXTOCCURRENCE = 29;
  public int JJTREADPASTNEXTOCCURRENCE = 30;
  public int JJTSQLSTATEMENT = 31;
  public int JJTWRAPPEDOBJECT = 32;
  public int JJTUNLABELLEDSTATEMENT = 33;
  public int JJTSTATEMENT = 34;
  public int JJTCASESTATEMENT = 35;
  public int JJTLOOPSTATEMENT = 36;
  public int JJTFORSTATEMENT = 37;
  public int JJTWHILESTATEMENT = 38;
  public int JJTIFSTATEMENT = 39;
  public int JJTFORINDEX = 40;
  public int JJTFORALLINDEX = 41;
  public int JJTFORALLSTATEMENT = 42;
  public int JJTGOTOSTATEMENT = 43;
  public int JJTRETURNSTATEMENT = 44;
  public int JJTEXITSTATEMENT = 45;
  public int JJTRAISESTATEMENT = 46;
  public int JJTCLOSESTATEMENT = 47;
  public int JJTOPENSTATEMENT = 48;
  public int JJTFETCHSTATEMENT = 49;
  public int JJTEMBEDDEDSQLSTATEMENT = 50;
  public int JJTPIPELINESTATEMENT = 51;
  public int JJTCONDITIONALCOMPILATIONSTATEMENT = 52;
  public int JJTSUBTYPEDEFINITION = 53;
  public int JJTFIELDDECLARATION = 54;
  public int JJTCOLLECTIONTYPEDEFINITION = 55;
  public int JJTCOLLECTIONDECLARATION = 56;
  public int JJTOBJECTDECLARATION = 57;
  public int JJTCALLSPECTAIL = 58;
  public int JJTCURSORUNIT = 59;
  public int JJTCURSORSPECIFICATION = 60;
  public int JJTCURSORBODY = 61;
  public int JJTEXPRESSION = 62;
  public int JJTCOMPILATIONEXPRESSION = 63;
  public int JJTASSIGNMENT = 64;
  public int JJTCASEEXPRESSION = 65;
  public int JJTLIKEEXPRESSION = 66;
  public int JJTTRIMEXPRESSION = 67;
  public int JJTOBJECTEXPRESSION = 68;
  public int JJTCONDITIONALOREXPRESSION = 69;
  public int JJTCONDITIONALANDEXPRESSION = 70;
  public int JJTEQUALITYEXPRESSION = 71;
  public int JJTRELATIONALEXPRESSION = 72;
  public int JJTADDITIVEEXPRESSION = 73;
  public int JJTSTRINGEXPRESSION = 74;
  public int JJTMULTIPLICATIVEEXPRESSION = 75;
  public int JJTUNARYEXPRESSION = 76;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 77;
  public int JJTPRIMARYEXPRESSION = 78;
  public int JJTPRIMARYPREFIX = 79;
  public int JJTPRIMARYSUFFIX = 80;
  public int JJTLITERAL = 81;
  public int JJTSTRINGLITERAL = 82;
  public int JJTBOOLEANLITERAL = 83;
  public int JJTNULLLITERAL = 84;
  public int JJTMULTISETCONDITION = 85;
  public int JJTNUMERICLITERAL = 86;
  public int JJTLABEL = 87;
  public int JJTNAME = 88;
  public int JJTQUALIFIEDNAME = 89;
  public int JJTARGUMENTS = 90;
  public int JJTARGUMENTLIST = 91;
  public int JJTARGUMENT = 92;
  public int JJTVARIABLEORCONSTANTDECLARATION = 93;
  public int JJTDATATYPEDECLARATION = 94;
  public int JJTPRAGMA = 95;
  public int JJTEXCEPTIONDECLARATION = 96;
  public int JJTPARALLELCLAUSE = 97;
  public int JJTTABLE = 98;
  public int JJTTABLECOLUMN = 99;
  public int JJTVIEW = 100;
  public int JJTVIEWCOLUMN = 101;
  public int JJTCOMMENT = 102;
  public int JJTTYPEMETHOD = 103;
  public int JJTTYPESPECIFICATION = 104;
  public int JJTALTERTYPESPEC = 105;
  public int JJTATTRIBUTEDECLARATION = 106;
  public int JJTATTRIBUTE = 107;
  public int JJTPRAGMACLAUSE = 108;
  public int JJTTRIGGERUNIT = 109;
  public int JJTTRIGGERTIMINGPOINTSECTION = 110;
  public int JJTCOMPOUNDTRIGGERBLOCK = 111;
  public int JJTNONDMLTRIGGER = 112;
  public int JJTDDLEVENT = 113;
  public int JJTDATABASEEVENT = 114;
  public int JJTNONDMLEVENT = 115;
  public int JJTALTERTRIGGER = 116;
  public int JJTKEYWORD_RESERVED = 117;
  public int JJTKEYWORD_UNRESERVED = 118;
  public int JJTID = 119;
  public int JJTUNQUALIFIEDID = 120;
  public int JJTQUALIFIEDID = 121;
  public int JJTTYPEKEYWORD = 122;
  public int JJTJAVAINTERFACECLASS = 123;
  public int JJTEQUALSOLDIDNEWID = 124;


  public String[] jjtNodeName = {
    "Input",
    "SqlPlusCommand",
    "Global",
    "Block",
    "PackageSpecification",
    "PackageBody",
    "DeclarativeUnit",
    "DeclarativeSection",
    "CompilationDeclarationFragment",
    "ProgramUnit",
    "ObjectNameDeclaration",
    "FormalParameter",
    "MethodDeclaration",
    "MethodDeclarator",
    "FormalParameters",
    "VariableOrConstantDeclarator",
    "VariableOrConstantDeclaratorId",
    "VariableOrConstantInitializer",
    "Datatype",
    "CompilationDataType",
    "CollectionTypeName",
    "ScalarDataTypeName",
    "DateTimeLiteral",
    "ExceptionHandler",
    "Skip2NextTerminator",
    "Skip2NextOccurrence",
    "SkipPastNextOccurrence",
    "Skip2NextTokenOccurrence",
    "SkipPastNextTokenOccurrence",
    "Read2NextOccurrence",
    "ReadPastNextOccurrence",
    "SqlStatement",
    "WrappedObject",
    "UnlabelledStatement",
    "Statement",
    "CaseStatement",
    "LoopStatement",
    "ForStatement",
    "WhileStatement",
    "IfStatement",
    "ForIndex",
    "ForAllIndex",
    "ForAllStatement",
    "GotoStatement",
    "ReturnStatement",
    "ExitStatement",
    "RaiseStatement",
    "CloseStatement",
    "OpenStatement",
    "FetchStatement",
    "EmbeddedSqlStatement",
    "PipelineStatement",
    "ConditionalCompilationStatement",
    "SubTypeDefinition",
    "FieldDeclaration",
    "CollectionTypeDefinition",
    "CollectionDeclaration",
    "ObjectDeclaration",
    "CallSpecTail",
    "CursorUnit",
    "CursorSpecification",
    "CursorBody",
    "Expression",
    "CompilationExpression",
    "Assignment",
    "CaseExpression",
    "LikeExpression",
    "TrimExpression",
    "ObjectExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "StringExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "UnaryExpressionNotPlusMinus",
    "PrimaryExpression",
    "PrimaryPrefix",
    "PrimarySuffix",
    "Literal",
    "StringLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "MultiSetCondition",
    "NumericLiteral",
    "Label",
    "Name",
    "QualifiedName",
    "Arguments",
    "ArgumentList",
    "Argument",
    "VariableOrConstantDeclaration",
    "DatatypeDeclaration",
    "Pragma",
    "ExceptionDeclaration",
    "ParallelClause",
    "Table",
    "TableColumn",
    "View",
    "ViewColumn",
    "Comment",
    "TypeMethod",
    "TypeSpecification",
    "AlterTypeSpec",
    "AttributeDeclaration",
    "Attribute",
    "PragmaClause",
    "TriggerUnit",
    "TriggerTimingPointSection",
    "CompoundTriggerBlock",
    "NonDMLTrigger",
    "DDLEvent",
    "DatabaseEvent",
    "NonDMLEvent",
    "AlterTrigger",
    "KEYWORD_RESERVED",
    "KEYWORD_UNRESERVED",
    "ID",
    "UnqualifiedID",
    "QualifiedID",
    "TypeKeyword",
    "JavaInterfaceClass",
    "EqualsOldIDNewID",
  };
}
/* JavaCC - OriginalChecksum=b2a2579a7a7d9170078a1bb2807ce982 (do not edit this line) */
