/**
 * BSD-style license; for more info see http://pmd.sourceforge.net/license.html
 */

/* Generated By:JJTree: Do not edit this line. ASTInlineConstraint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package net.sourceforge.pmd.lang.plsql.ast;

public class ASTInlineConstraint extends net.sourceforge.pmd.lang.plsql.ast.AbstractPLSQLNode {
    private ConstraintType type;

    public ASTInlineConstraint(int id) {
        super(id);
    }

    public ASTInlineConstraint(PLSQLParser p, int id) {
        super(p, id);
    }

    void setType(ConstraintType type) {
        this.type = type;
    }

    public ConstraintType getType() {
        return type;
    }

    public boolean isUnique() {
        return type == ConstraintType.UNIQUE;
    }

    public boolean isPrimaryKey() {
        return type == ConstraintType.PRIMARY;
    }

    public boolean isCheck() {
        return type == ConstraintType.CHECK;
    }

    /**
     * Accept the visitor.
     **/
    @Override
    public Object jjtAccept(PLSQLParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=6100a18102b66b39df188afb7c4dcf8a (do not edit this line) */
