name: Pull Request Build

on:
  pull_request:
  merge_group:

# if another commit is added to the PR (same github.head_ref), then cancel already running jobs
# and start a new build
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  LANG: 'en_US.UTF-8'

jobs:
  reusable-build:
    needs: check-version
    runs-on: ubuntu-latest
    timeout-minutes: 120
    uses: ./.github/workflows/reusable-build.yml

  regressiontester:
    needs: compile
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gradle/caches
            ~/work/pmd/target/repositories
            vendor/bundle
          key: regressiontester-${{ hashFiles('.ci/files/project-list.xml', 'Gemfile.lock') }}
          restore-keys: regressiontester-
      - uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: pmd-dist/target
      - name: Setup bundler
        run: |
          bundle config set --local gemfile .ci/files/Gemfile
          bundle config set --local path vendor/bundle
          bundle install
      - name: Prepare HOME/openjdk11
        run: |
          ln -sfn "${JAVA_HOME_11_X64}" "${HOME}/openjdk11"
      - name: Run pmdtester
        env:
          # this only works if the triggering event of this workflow is "pull_request"
          PMD_CI_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          PMD_CI_BRANCH: ${{ github.base_ref }}
        run: |
          echo "::group::Fetching additional commits"
          # git clone initially only fetched with depth 2. Regression tester
          # needs more history, so we'll fetch more here
          # and create local branches as well (${PMD_CI_BRANCH} and pr-fetch)
      
          echo "Fetching 25 commits for ${PMD_CI_BRANCH} and pull/${PMD_CI_PULL_REQUEST_NUMBER}/head"
          git fetch --no-tags --depth=25 origin "${PMD_CI_BRANCH}:${PMD_CI_BRANCH}" "pull/${PMD_CI_PULL_REQUEST_NUMBER}/head:pr-fetch"
      
          # if the PR is older, base might have advanced more than 25 commits... fetch more, up to 150
          for i in $(seq 1 3); do
            if [ -z "$( git merge-base "${PMD_CI_BRANCH}" "pr-fetch" )" ]; then
              echo "No merge-base yet - fetching more commits... (try $i)"
              git fetch --no-tags --deepen=50 origin "${PMD_CI_BRANCH}:" "pull/${PMD_CI_PULL_REQUEST_NUMBER}/head:pr-fetch"
            fi
          done
          echo "Merge base is: $( git merge-base "${PMD_CI_BRANCH}" "pr-fetch" )"
          echo "::endgroup::"
      
          echo "::group::Running pmdtester on branch ${PMD_CI_BRANCH}"
          bundle exec ruby .ci/files/pmdtester.rb
          echo "::endgroup::"
      - name: Workaround actions/upload-artifact#176
        run: |
          echo "artifacts_path=$(realpath ..)" >> "${GITHUB_ENV}"
      - name: Upload regression tester report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-regression-tester
          if-no-files-found: error
          path: ${{ env.artifacts_path }}/target/reports/diff
